### ISSUE TITLE
Global: Book Title and Subtitle separated into two fields

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#14] opened 2015-06-30 15:05 UTC
Title Green, Subtitle brown. Pick up brown color from copy on the homepage.

**Comment by BigActual** [comment] 2015-07-01 15:17
All titles in both the shop and the books section. client requests a "half line" of space between title and sub-title.

**Comment by joelworsham** [comment] 2015-07-02 13:49
Duplicate of #25

**Closed as completed by joelworsham** 2015-07-02 13:49 UTC
Labels: duplicate, enhancement
